version: 2.1

##################################### YAML ANCHORS  ############################################

tag-trigger: &tag-trigger
  tags:
    only: /^v.*/

jobs:
  ubuntu-build:
    docker:
      - image: ubuntu:22.04
    steps:
      - run:
          name: Install Ubuntu 22.04 deps
          command: |
            apt update && apt install -y git ruby ruby-dev libffi-dev build-essential
      - run:
          name: Add github.com to known hosts
          command: |
            touch /root/.ssh/known_hosts
            ssh-keyscan github.com >> /root/.ssh/known_hosts
      - checkout
      - run:
          name: Ubuntu 22.04 package
          command: |
            ./build.sh
      - persist_to_workspace:
          root: ./pkg
          paths:
            - "*.deb"

  ubi8-build:
    docker:
      - image: registry.access.redhat.com/ubi8/ruby-30:1
        user: root
    steps:
      - run:
          name: Install UBI8 deps
          command: |
            yum -y install rpm-build yajl
      - run:
          name: Add github.com to known hosts
          command: |
            touch /root/.ssh/known_hosts
            ssh-keyscan github.com >> /root/.ssh/known_hosts
      - checkout
      - run:
          name: UBI8 package
          command: |
            ./build.sh
      - persist_to_workspace:
          root: ./pkg
          paths:
            - "*.rpm"

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${CIRCLE_TAG} ./artifacts/

workflows:
  version: 2
  build:
    jobs:
      - ubuntu-build:
          filters:
            <<: *tag-trigger
      - ubi8-build:
          filters:
            <<: *tag-trigger
      - publish-github-release:
          requires:
            - ubuntu-build
            - ubi8-build
          filters:
            <<: *tag-trigger
            branches:
              ignore: /.*/
